#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
echo "Enter your role (admin/user/guest):"

number=1

while [ $number -le 20 ]
do
    case $number in
        4)
            echo "$number"
            echo "bad luck from China"
            ;;
        9)
            echo "$number"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$number"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$number"
            ;;
    esac
    ((number++))
done

